server.port=${EDGE_PORT:8080}
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
orders.url=${ORDERS_URL:http://localhost:8081}
inventory.url=${INVENTORY_URL:http://localhost:8082}
customers.url=${CUSTOMERS_URL:http://localhost:8083}
